#!/usr/bin/env bash
set -ex

HERE=${BASH_SOURCE%/*}
if [[ ($# -eq 0) ]]; then
    echo "Usage: ./run MONTAGU_API_METRICS_ABS_PATH"
    exit -1;
fi

HERE=${BASH_SOURCE%/*}
api_metrics=$1

docker build --tag montagu_api_metrics --file  $HERE/Dockerfile $HERE

docker run --rm \
    --network=montagu_default \
    -p 5000:80 \
    -v $1:/api_metrics  \
    --detach \
    --name=montagu_api_metrics_1 \
    --restart=unless-stopped
    montagu_api_metrics
