#!/usr/bin/env bash
set -ex

if [[ ($# -eq 0) ]]; then
    echo "Usage: ./run
    exit -1;
fi

HERE=${BASH_SOURCE%/*}

docker build --tag montagu_api_metrics --file  $HERE/Dockerfile $HERE

docker run --rm \
    -p 5000:80 \
    --detach \
    --name=bb8_metrics_1 \
    montagu_api_metrics
